name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Set up Python
      uses: actions/checkout@master
    - name: Install dependencies
      run: |
        pip install -U sphinx sphinx-rtd-theme recommonmark sphinx-markdown-tables
        sphinx-build -b html ./docs/ .
