name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/checkout@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -v
        pip install -U sphinx sphinx-rtd-theme recommonmark sphinx-markdown-tables
        sphinx-build -b html ./docs/ .
